name: 'Reqover'
description: 'Publish reqover results'
inputs:
  server-url:
    description: 'Reqover server url'
    required: false
    default: 'https://reqover-io.herokuapp.com'
  build-id:
    description: 'Build id'
    required: true
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
runs:
  using: 'node16'
  main: 'index.js'