on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Reqover action 
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Reqover action step
        uses: ./
        with:
          build-id: 'td0wsmc2xlet'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
