on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Reqover action 
    steps:
      - name: Reqover action step
        uses: reqover/reqover-action@test
        with:
          build-id: 'td0wsmc2xlet'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
