on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Reqover action 
    steps:
      - name: Reqover action step
        id: hello
        uses: reqover/reqover-action@master
        with:
          build-id: 'td0wsmc2xlet'
          github-token: ${{ secrets.GITHUB_TOKEN }}
